app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import Config

bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    bootstrap.init_app(app)
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template


@bp.route('/index', methods=['GET', 'POST'])
@bp.route('/', methods=['GET', 'POST'])
def index():
    return render_template('main/index.html', title='Главная')


@bp.route('/projects', methods=['GET', 'POST'])
def projects():
    return render_template('main/projects.html', title='Проекты')

app/templates/main/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {{ title }} - Аминов Дамир Азатович
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="icon" href="{{ url_for('static', filename='icons/favicon.ico') }}">
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default" style="min-width: 1252px">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Дамир Азатович</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Главная</a></li>
                    <li><a href="{{ url_for('main.projects') }}">Проекты</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    {% block app_content %}{% endblock %}
    {% block footer %}
        <div class="text-center">
            &copy; Аминов Дамир Азатович - <a href="https://damirazatovich.com">damirazatovich.com</a>
        </div>
    {% endblock %}
{% endblock %}

app/templates/main/index.html
{% extends 'main/base.html' %}

{% block app_content %}
    <div class="container mt-4" style="min-width: 1170px">
        <table style="margin: 60px auto 35px;">
            <tr>
                <td><img src="{{ url_for('static', filename = 'images/Avatar.jpg') }}" width="115%" height="115%" style="border-radius: 100px"></td>
                <td><table style="margin-left: 50px">
                    <tr>
                        <td><b>Аминов Дамир Азатович <br> Python программист </b></td>
                    </tr>
                    <tr>
                        <td style="padding: 6px">Дата рождения</td>
                        <td class="text-center">09 декабря 2000 года</td>
                    </tr>
                    <tr>
                        <td style="padding: 6px">Место проживания:</td>
                        <td class="text-center">г. Екатеринбург</td>
                    </tr>
                    <tr>
                        <td style="padding: 6px">Телефон:</td>
                        <td class="text-center"><a href="tel:+79222933944">+7 (922) 293-39-44</a></td>
                    </tr>
                    <tr>
                        <td style="padding: 6px">Email: </td>
                        <td class="text-center"><a href="mailto:damiraminov1@yandex.ru">damiraminov1@yandex.ru</a></td>
                    </tr>
                    <tr>
                        <td style="padding: 6px">Github: </td>
                        <td class="text-center"><a href="https://github.com/hecronk">
                            <img src="{{ url_for('static', filename = 'icons/github.svg') }}"></a>
                            <a href="https://github.com/hecronk">перейти</a>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 6px">Telegram: </td>
                        <td class="text-center"><a href="https://t.me/hecronk">
                            <img src="{{ url_for('static', filename = 'icons/telegram.svg') }}"></a>
                            <a href="https://t.me/hecronk">перейти</a>
                        </td>
                    </tr>
                </table></td>
            </tr>
        </table>
        <br>
            <div class="text-center">
                <h3>Опыт работы</h3>
            </div>
        <br>
        <table>
            <tr>
                <td style="padding: 6px; width: 200px" class="text-center">01.07.2020 - 23.07.2020</td>
                <td style="padding: 6px">&bull; Прохождение учебной практики по программированию python.
                    Исследование датасета с использованием библиотек python (pandas, matplotlib, sklearn).</td>
            </tr>
            <tr>
                <td style="padding: 6px; width: 200px" class="text-center">07.07.2021 - 23.07.2021</td>
                <td style="padding: 6px">&bull; Прохождение учебной практики по программированию python в компании ООО “К ТЕЛЕКОМ”.
                    Разработка сервиса для загрузки статических файлов (CherryPy, Jinja2).</td>
            </tr>
            <tr>
                <td style="padding: 6px; width: 200px" class="text-center">30.12.2021 - 27.01.2022</td>
                <td style="padding: 6px">&bull; Наставник онлайн курса Python-разработки в IT School Maxima.
                    Ответы на вопросы учеников курса в чате. Проверка домашних заданий. Проведение онлайн консультаций.</td>
            </tr>
            <tr>
                <td style="padding: 6px; width: 200px" class="text-center">18.04.2022 - наст. время.</td>
                <td style="padding: 6px">&bull; Python-разработка программного обеспечения в ООО LamArt.</td>
            </tr>
        </table>
        <br>
            <div class="text-center">
                <h3>Образование</h3>
            </div>
        <br>
        <table>
            <tr>
                <td style="padding: 6px; width: 200px" class="text-center">2016 - 2019</td>
                <td style="padding: 6px">Лицей ГБПОУ "Свердловский областной медицинский колледж"</td>
            </tr>
            <tr>
                <td style="padding: 6px; width: 200px" class="text-center">2019 - наст. время.</td>
                <td style="padding: 6px">Уральский Государственный Университет Путей Сообщения.
                    Направление подготовки: 09.03.02 “Информационные системы и технологии”
                    (3 курс, очное отделение, бакалавр, бюджет)</td>
            </tr>
        </table>
        <br>
            <b>Дополнительное образование</b>
        <br>
        <table>
            <tr>
                <td style="padding: 6px; width: 200px" class="text-center">2010 - 2018</td>
                <td style="padding: 6px">Английский язык. Окончил общий курс, соответствующий уровню B2 UPPER-INTERMEDIATE,
                    согласно Общеевропейской шкале уровней владения иностранным языком CEFR.</td>
            </tr>
            <tr>
                <td style="padding: 6px; width: 200px" class="text-center">2021</td>
                <td style="padding: 6px">Окончил курс “Анализ данных в индустрии” от Тинькофф Образование</td>
            </tr>
        </table>
        <br>
            <div class="text-center">
                <h3>Навыки</h3>
            </div>
        <br>
        <p>
            &bull; Разработка приложений на Python (frameworks: Flask, CherryPy, PyTelegramBotApi, aiogram), C#, Unity (Android); <br>
            &bull; Знание Docker и docker-compose; <br>
            &bull; Знание языка запросов PostgreSQL, MySQL, SQLite; <br>
            &bull; Опыт написания ботов для Telegram; <br>
            &bull; Знание языка разметки HTML + CSS; <br>
            &bull; Опыт создания виртуальной частной сети (VPN); <br>
            &bull; Уверенный пользователь Linux, Windows, Android; <br>
            &bull; Вождение автомобилей категории B, стаж 2 года; <br>
            &bull; Опыт администрирования: настройка, поддержка периферийных устройств, настройка и обслуживание
            ПК и Android (переустановка Windows, перепрошивка Android); <br>
            &bull; Виртуализация – Virtual Box, VMware; <br>
            &bull; Навык слепой печати; <br>
            &bull; Знание Git-Console. <br>
        </p>
        <div class="text-center">
            <a href="{{ url_for('main.projects') }}">
                <button type="button" class="btn btn-default" style="margin: 100px; width: 300px; height: 50px">Посмотреть мои проекты</button>
            </a>
        </div>
    </div>
{% endblock %}

app/templates/main/projects.html
{% extends 'main/base.html' %}

{% block title %}
    Мои проекты - Аминов Дамир Азатович
{% endblock %}


{% block app_content %}
    <div class="container mt-4" style="min-width: 1170px">
        <div class="text-center">
            <h3>Мои основные проекты:</h3>
        </div>
        <div>
            <p>
                <a href="https://github.com/hecronk/TimetableHecronkUSPUTelegramBot" style="text-decoration: none">
                    <img src="{{ url_for('static', filename = 'icons/telegram.svg') }}" alt="" width="120" height="96" class="d-inline-block align-text">
                </a>
                <a href="https://github.com/hecronk/TimetableHecronkUSPUTelegramBot">Бот в Telegram</a>
            </p>
            <p>
                УрГПУ Расписание - бот для просмотра актуального расписания. Написан на Python, с использованием aiogram. <br>
                Работает 24/7 и выполняет роль агрегатора актуального расписания УрГПУ. <a href="https://t.me/USPU_TIMETABLE_bot">Открыть бота в Telegram</a>
            </p>
            <p>
                <img src="{{ url_for('static', filename = 'images/TelegramBotScreenshot1.jpg') }}"> <br><br>
                <img src="{{ url_for('static', filename = 'images/TelegramBotScreenshot2.jpg') }}">
            </p>
            <p>
                <a href="https://github.com/hecronk/FileUploadService" style="text-decoration: none">
                    <img src="{{ url_for('static', filename = 'icons/file-earmark-arrow-up-fill.svg') }}" alt="" width="120" height="96" class="d-inline-block align-text">
                </a>
                <a href="https://github.com/hecronk/FileUploadService">Облачное хранилище</a>
            </p>
            <p>
                Облачное хранилище - сервис с веб интерфейсом для загрузки и хранения файлов. Написан на Python, с использованием веб-фреймворка CherryPy. <br>
                Получение файлов реализовано с помощью API.
            </p>
            <p>
                <img src="{{ url_for('static', filename = 'images/FileUploadServiceScreenshot1.jpg') }}">
                <img src="{{ url_for('static', filename = 'images/FileUploadServiceScreenshot2.jpg') }}">
                <img src="{{ url_for('static', filename = 'images/FileUploadServiceScreenshot3.jpg') }}">
                <img src="{{ url_for('static', filename = 'images/FileUploadServiceScreenshot4.jpg') }}">
                <img src="{{ url_for('static', filename = 'images/FileUploadServiceScreenshot5.jpg') }}">
            </p>
            <p>
                <a href="https://github.com/hecronk/FlaskLearning" style="text-decoration: none">
                    <img src="{{ url_for('static', filename = 'icons/chat-right-text-fill.svg') }}" alt="" width="120" height="96" class="d-inline-block align-text">
                </a>
                <a href="https://github.com/hecronk/FlaskLearning">Социальная сеть</a>
            </p>
            <p>
                Социальная сеть - проект, написанный на Python, который создавался с целью изучения веб-фреймворка Flask. <br>
                Имеет основной функционал социальных сетей (пользователи, личные страницы, подписки, лента). Реализована система регистрации пользователей, восстановления пароля.
            </p>
            <p>
                <img src="{{ url_for('static', filename = 'images/FlaskLearningScreenshot1.jpg') }}">
                <img src="{{ url_for('static', filename = 'images/FlaskLearningScreenshot2.jpg') }}">
                <img src="{{ url_for('static', filename = 'images/FlaskLearningScreenshot3.jpg') }}">
                <img src="{{ url_for('static', filename = 'images/FlaskLearningScreenshot4.jpg') }}">
                <img src="{{ url_for('static', filename = 'images/FlaskLearningScreenshot5.jpg') }}">
            </p>
        </div>
    </div>
{% endblock %}